[package]
name = "rust-os"
version = "0.1.0"
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
virtio-drivers = "0.1.0"
buddy_system_allocator = "0.8.0"
